### ISSUE TITLE
AssertionError in group_symbols

### ISSUE THREAD

**Issue by thiagokokada** [hcpl/xkbgroup#1]
So I am getting an assertion error:

```
Python 3.6.0 (default, Dec 24 2016, 08:03:08) 
[GCC 6.2.1 20160830] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xkbgroup import XKeyboard
>>> xkb = XKeyboard()
>>> xkb.groups_symbols
3 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/m45t3r/Source/xkbgroup/venv/lib/python3.6/site-packages/xkbgroup/core.py", line 261, in groups_symbols
    return _ListProxy(symdata.symbol for symdata in self._symboldata_list)
  File "/home/m45t3r/Source/xkbgroup/venv/lib/python3.6/site-packages/xkbgroup/core.py", line 428, in _symboldata_list
    return _parse_symbols(b_symbol_str.decode(), ["pc", "inet", "group"])
  File "/home/m45t3r/Source/xkbgroup/venv/lib/python3.6/site-packages/xkbgroup/core.py", line 487, in _parse_symbols
    assert len(indices) == len(set(indices))    # No doubles
AssertionError
>>> 
```

From my debugging, the problem seems to be this:

```
print(symboldata_list)
[SymbolData(symbol='br', variant=None, index=0), SymbolData(symbol='us', variant='intl', index=1), SymbolData(symbol='terminate', variant='ctrl_alt_bksp', index=0)]
```
As you can see, there is two layouts reporting `index=0`. This comes from my `/etc/X11/xorg.conf.d/00-keyboard`, set by localectl:

```
# Read and parsed by systemd-localed. It's probably wise not to edit this file
# manually too freely.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "br"
        Option "XkbModel" "abnt2"
        Option "XkbOptions" "terminate:ctrl_alt_bksp"
EndSection
```
So for some reason, xkbgroup is detecting XkbOptions as another layout. This shouldn't happen: `terminate: ctrl_alt_bksp` is not actually a layout, it is part from layout br.

**Comment by hcpl** [comment]
@m45t3r, thank you for the detailed report!

Using `setxkbmap` with the same settings as in your `/etc/X11/xorg.conf.d/00-keyboard`
```sh
$ setxkbmap -layout "br" -model "abnt2" -option "terminate:ctrl_alt_bksp" -verbose
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+br+inet(evdev)+terminate(ctrl_alt_bksp)
geometry:   pc(pc104)
```
reveals that there is another non-symbol name `terminate` apart from `pc`, `inet` and `group` (which are present under my settings):
```sh
$ setxkbmap -layout "us,ru,ua" -option "grp:alt_shift_toggle" -verbose
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+ua:2+ru:3+inet(evdev)+group(alt_shift_toggle)
geometry:   pc(pc104)
```
So adding `terminate` to the set of names to ignore should solve this specific issue.

**Comment by hcpl** [comment]
Regarding long-term solutions:

Currently, non-symbol names are filtered out manually and [this part is hardcoded](https://github.com/hcpl/xkbgroup/blob/master/xkbgroup/core.py#L428). This is based on the assumption that the set of non-symbol names is finite and immutable (but the set of symbol ones is possibly infinite).

It's hard to include every possible non-symbol name. So more gracefully this could be done by allowing users to specify their own set of names to filter out while still providing the default set.

**Comment by hcpl** [comment]
@m45t3r, just made a commit and uploaded a new version to PyPI. Try it out!

**Comment by thiagokokada** [comment]
Seems to work now, thanks!
